#!/bin/bash
echo "Sourcing .bashrc..."
source ~/.bashrc

echo "Purging modules..."
module purge

echo "Activating alignment conda env..."
conda activate alignPYQT

echo "cd'ing to swift-ir and pulling changes..."
cd $WORK/swift-ir
git pull

echo "Setting QT API environment flag..."
unset QT_API
export QT_API=pyqt6

echo "Loading modules..."
ml intel/19.1.1 swr/21.2.5 impi/19.0.9 fftw3/3.3.10
#ml intel/19.1.1 impi/19.0.9

#echo "Loading python_cacher module..."
#ml python_cacher