#!/bin/bash
# INSTRUCTIONS TO RUN AlignEM-SWiFT ON Lonestar6 AT TACC
# (DEPLOYMENT BY CONDA ENVIRONMENT STRATEGY)

# NOTES:
#     CONNECT TO Lonestar6 THROUGH THE VIS PORTAL. CHOOSE DCV SESSION.
#     PURGE MODULES (HAVE NO MODULES LOADED) WHEN CREATING OR ACTIVATING A CONDA ENV

#######################################
# RUN ONCE
#######################################

echo "Setting things up..."

echo "Changing directory to WORK directory..."
cd $WORK

echo "Checking if miniforge (conda) is installed..."
if [ ! -d "$HOME/miniforge3" ]; then
  echo "Setting Miniforge (conda) installer..."
  wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh
  echo "$HOME/miniforge3 does not exist - Installing miniforge..."
  curl -LO https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh
  sh $WORK/Miniforge3-Linux-x86_64.sh -b
  $WORK/miniforge3/condabin/conda init
fi

if [ ! -d "$HOME/miniforge3" ]; then
  echo "not installed"
fi

#echo "Installing a recent version of nvm..."
#curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
#nvm install stable

echo "Sourcing .bashrc..."
source ~/.bashrc

echo "Turning off annoying conda base environment so DCV will work..."
conda config --set auto_activate_base false


echo "Checking if swift-ir exists in $WORK..."
if [ ! -d "$WORK/swift-ir" ]; then
  echo "Cloning AlignEM-SWiFT..."
  git clone https://github.com/mcellteam/swift-ir.git
fi

echo "Changing directory to swift-ir..."
cd swift-ir/

echo "Checking out development_ng branch..."
git checkout development_ng
git pull

echo "Purging modules..."
module purge

echo "Removing alignTACC env if it exists..."
conda env remove -n alignPYQT

echo "Creating Conda environment from tacc.yml..."
conda env create --name=alignPYQT --file tacc.yml python=3.9

#echo "Adding alignEM.py to PATH in .bashrc..."
#echo 'export PATH="$PATH:$WORK/swift-ir/alignEM.py"' >> ~/.bashrc

if alias align >/dev/null 2>&1; then
  echo "align alias already exists - continuing..."
else
  echo "alias align='swr numactl --preferred=1 python3 $WORK/swift-ir/alignEM.py'" >> ~/.bashrc
fi

echo "Complete."

