#!/bin/bash

echo "Loading intel/19.1.1 module..."
ml intel/19.1.1
echo "Loading swr/21.2.5 module..."
ml swr/21.2.5
echo "Loading impi/19.0.9 module..."
ml impi/19.0.9
echo "Loading fftw3/3.3.10 module..."
ml fftw3/3.3.10
echo "Activating Preconfigured Conda Environment..."
conda activate /work/08507/joely/ls6/miniconda3/envs/alignTACC1024


echo "Checking out development_ng branch..."
git fetch
git checkout remotes/origin/fb30_joel
git pull
git log -1
python3 $WORK/swift-ir/alignEM.py